logging:
    level:
        guru.ysy.aiexpert: DEBUG
jdk:
    vendor:
        name: Oracle-JDK
        version: ${java.version}
gradle:
    version: 8.8
    DSL: Kotlin
spring:
    application:
        name: zhipu-SpringAI
        version: 0.0.1-SNAPSHOT
        description: DEMO Spring AI project with Zhipu AI
    output:
        ansi:
            enabled: always
    config:
        import: classpath:env/keys.env[.properties]
    ai:
        zhipuai:
            api-key: ${ZHIPU_API_KEY}
#             the following config is not necessary for image generation
#             chat:
#                 options:
#                     model: GLM-3-Turbo
#             image:
#                 enabled: true

